tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - tf-env: |
      brew update && brew upgrade && brew install \
      gawk coreutils pre-commit tfenv terraform-docs \
      tflint tfsec instrumenta/instrumenta/conftest \
      && brew cleanup
  - tf-default: |
      tfenv install 0.11.14 && tfenv use 0.11.14


ports:
  - port: 3000
    onOpen: open-browser
  - port: 4567
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - HashiCorp.terraform
    - AmazonWebServices.aws-toolkit-vscode  